In [6]:
import numpy as np

Creamos un array a traves de la función arange y reshape, la T traspone el array

In [33]:
a = np.arange(1,16,1).reshape(3,5).T

In [34]:
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [35]:
a[2]

array([ 3,  8, 13])

In [36]:
b=([a[2],a[4]])

In [37]:
b

[array([ 3,  8, 13]), array([ 5, 10, 15])]

In [39]:
b[1,1]

7

Creamos una matriz de numeros aleatorios

In [67]:
a = np.random.rand(10,3)

In [68]:
a

array([[ 0.27635689,  0.46329921,  0.32730257],
       [ 0.15389169,  0.19621131,  0.20132416],
       [ 0.4382395 ,  0.332557  ,  0.85784009],
       [ 0.19367565,  0.85457211,  0.72306493],
       [ 0.16413232,  0.81090429,  0.77217773],
       [ 0.37816302,  0.97208196,  0.76166853],
       [ 0.33591457,  0.24957747,  0.65261186],
       [ 0.78487113,  0.6852539 ,  0.07805634],
       [ 0.81359053,  0.70940736,  0.37892133],
       [ 0.32173883,  0.52243282,  0.15352348]])

In [181]:
ordenado=np.argsort(abs(a-0.5))

In [194]:
p=ordenado[:,0]

In [195]:
p

array([1, 2, 0, 2, 2, 0, 2, 1, 2, 1])

In [106]:
ordenado

array([[1, 2, 0],
       [2, 1, 0],
       [0, 1, 2],
       [2, 0, 1],
       [2, 1, 0],
       [0, 2, 1],
       [2, 0, 1],
       [1, 0, 2],
       [2, 1, 0],
       [1, 0, 2]])

In [130]:
p

array([1, 2, 0, 2, 2, 0, 2, 1, 2, 1])

In [196]:
a[np.arange(10),p[0:]]

array([ 0.46329921,  0.20132416,  0.4382395 ,  0.72306493,  0.77217773,
        0.37816302,  0.65261186,  0.6852539 ,  0.37892133,  0.52243282])

In [121]:
a

array([[ 0.27635689,  0.46329921,  0.32730257],
       [ 0.15389169,  0.19621131,  0.20132416],
       [ 0.4382395 ,  0.332557  ,  0.85784009],
       [ 0.19367565,  0.85457211,  0.72306493],
       [ 0.16413232,  0.81090429,  0.77217773],
       [ 0.37816302,  0.97208196,  0.76166853],
       [ 0.33591457,  0.24957747,  0.65261186],
       [ 0.78487113,  0.6852539 ,  0.07805634],
       [ 0.81359053,  0.70940736,  0.37892133],
       [ 0.32173883,  0.52243282,  0.15352348]])