Creamos un array a traves de la función arange y reshape, la T traspone el array

In [1]:
import numpy as np

In [2]:
a = np.arange(1,16,1).reshape(3,5).T

In [3]:
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

Generamos una nueva matriz que contenga la fila 2 y la fila 4

In [4]:
b=a[2::2]

In [5]:
b

array([[ 3,  8, 13],
       [ 5, 10, 15]])

EJERCICIO 2

Generamos una matriz 10 x 3 de números aleatorios

In [6]:
c = np.random.rand(10,3)

In [7]:
c

array([[ 0.25304215,  0.61168482,  0.38443781],
       [ 0.2821335 ,  0.39403322,  0.59054597],
       [ 0.54140684,  0.40320894,  0.40772088],
       [ 0.71127779,  0.23971113,  0.62495244],
       [ 0.1408357 ,  0.17454663,  0.04122548],
       [ 0.81818003,  0.38290811,  0.09345381],
       [ 0.26180301,  0.87675505,  0.83240153],
       [ 0.06388973,  0.54629153,  0.63930696],
       [ 0.03655929,  0.48628456,  0.47302359],
       [ 0.14269842,  0.03760326,  0.7681642 ]])

Elegimos el número mas cercano a 0.5 usando las funciones abs y argsort para encontrar dicha posición en la matriz

In [10]:
ordenado=np.argsort(abs(c-0.5))

In [11]:
ordenado

array([[1, 2, 0],
       [2, 1, 0],
       [0, 2, 1],
       [2, 0, 1],
       [1, 0, 2],
       [1, 0, 2],
       [0, 2, 1],
       [1, 2, 0],
       [1, 2, 0],
       [2, 0, 1]])

Queremos la primera columna del array ordenado

In [12]:
primeraColumna=ordenado[:,0]

In [13]:
primeraColumna

array([1, 2, 0, 2, 1, 1, 0, 1, 1, 2])

Creamos una nueva matriz con dichos numeros (los de la matriz 10*3), para ello obtenemos el tamaño de la matriz (numero de filas) usando la funcíon shape

In [14]:
tamanioMatriz=c.shape[0]

Creamos la nueva matriz 

In [16]:
nuevaMatriz=c[np.arange(tamanioMatriz),primeraColumna[0:]]

In [17]:
nuevaMatriz

array([ 0.61168482,  0.59054597,  0.54140684,  0.62495244,  0.17454663,
        0.38290811,  0.26180301,  0.54629153,  0.48628456,  0.7681642 ])

EJERCICIO 3

Cargamos los datos del fichero populations.txt en una variable

In [18]:
datosPoblacion = np.loadtxt('populations.txt')

In [19]:
datosPoblacion

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

Definimos un array que contenga las poblaciones a estudiar, es decir, sin los años

In [21]:
poblaciones = datosPoblacion[0:,1:]

Calculamos la media de las liebres, linces y zanahorias

In [22]:
poblaciones.mean(axis=0)

array([ 34080.95238095,  20166.66666667,  42400.        ])

Calculamos ahora la desviación estandar

In [23]:
poblaciones.std(axis=0)

array([ 20897.90645809,  16254.59153691,   3322.50622558])

Buscamos el año en el que la población de cada especie fue mayor, para ello obtenemos la posición en la cual esta el máximo de cada columna del array poblaciones, Esto lo hacemos usando la funcion argmax.

In [24]:
posicionMaximoPoblaciones = poblaciones.argmax(axis=0)

Una vez tenemos la posicionMaximoPoblaciones se obtiene los años para cada poblacion

In [25]:
aniosMaxPoblacion=datosPoblacion[posicionMaximoPoblaciones[:],0]

In [26]:
aniosMaxPoblacion

array([ 1903.,  1904.,  1900.])

In [35]:
print("Año de maxima poblacion en Liebres: ",aniosMaxPoblacion[0], ", Linces: ",aniosMaxPoblacion[1], ", Zanahorias: ", aniosMaxPoblacion[2])

Año de maxima poblacion en Liebres:  1903.0 , Linces:  1904.0 , Zanahorias:  1900.0


Veamos ahora que especie tiene la población más grande para cada año. Para esto obtenemos la posicion en la cual se encuentra la poblacion mayor en cada fila, usando la funcion argmax, pero esta vez para las filas

In [39]:
especies=np.array(["Liebre","Lince","Zanahoria"])

In [36]:
posicionMaximoPoblacionesAnio = poblaciones.argmax(axis=1)

In [37]:
posicionMaximoPoblacionesAnio

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

Mostramos por pantalla los años y la poblacion máxima para ese año

In [41]:
especies[posicionMaximoPoblacionesAnio]

array(['Zanahoria', 'Zanahoria', 'Liebre', 'Liebre', 'Lince', 'Lince',
       'Zanahoria', 'Zanahoria', 'Zanahoria', 'Zanahoria', 'Zanahoria',
       'Zanahoria', 'Liebre', 'Liebre', 'Liebre', 'Lince', 'Zanahoria',
       'Zanahoria', 'Zanahoria', 'Zanahoria', 'Zanahoria'], 
      dtype='<U9')

In [46]:
print("Datos: ",datosPoblacion[:,0],especies[posicionMaximoPoblacionesAnio])

Datos:  [ 1900.  1901.  1902.  1903.  1904.  1905.  1906.  1907.  1908.  1909.
  1910.  1911.  1912.  1913.  1914.  1915.  1916.  1917.  1918.  1919.
  1920.] ['Zanahoria' 'Zanahoria' 'Liebre' 'Liebre' 'Lince' 'Lince' 'Zanahoria'
 'Zanahoria' 'Zanahoria' 'Zanahoria' 'Zanahoria' 'Zanahoria' 'Liebre'
 'Liebre' 'Liebre' 'Lince' 'Zanahoria' 'Zanahoria' 'Zanahoria' 'Zanahoria'
 'Zanahoria']


Ahora vemos en que años hay poblaciones por encima de 50000. Para esto hacemos uso de la función Any.

In [47]:
Mayor50000=np.any(poblaciones>50000,axis=1)

Obtenemos ahora los años en que la población esta por encima de la cifra anterior

In [50]:
datosPoblacion[Mayor50000,0]

array([ 1902.,  1903.,  1904.,  1912.,  1913.,  1914.,  1915.])

Determinamos ahora los 2 primeros años en el cual cada especie tenia su población mas baja. Para esto se hace uso de la función argsort que nos ordena nuestra matriz y cogemos las dos primeras filas

In [51]:
minAniosPoblaciones=poblaciones.argsort(axis=0)[:2]

In [52]:
minAniosPoblaciones

array([[17,  0, 16],
       [16,  1,  3]])

Ahora obtenemos los años, como tenemos la posición, vamos directamente a nuestros datos y de esta forma lo obtenemos.

In [53]:
datosPoblacion[minAniosPoblaciones,0]

array([[ 1917.,  1900.,  1916.],
       [ 1916.,  1901.,  1903.]])